### ISSUE TITLE
Cannot open Saved windows no more

### ISSUE THREAD

**Issue by ferrangomis** [stefanXO/Tab-Manager-Plus#207]
I get the following error in the console:
Invalid value for bounds. Bounds must be at least 50% within visible screen space.
caught (in promise) TypeError: Cannot read properties of undefined (reading 'tabs')
    at Session._callee$ (Session.js:173:30)
    at tryCatch (babel-polyfill.js:6517:40)
    at Generator.invoke [as _invoke] (babel-polyfill.js:6743:22)
    at prototype.<computed> [as next] (babel-polyfill.js:6569:21)
    at step (Session.js:1:747)
    at Session.js:1:907
_

**Comment by ferrangomis** [comment]
This started happening today, not sure if it might have something to do with the Chrome update.

**Comment by ferrangomis** [comment]
This is a fantastic extension by the way!!

**Comment by ferrangomis** [comment]
It's working again! Thanks!
